# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: threat_matches.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14threat_matches.proto\"\x96\x01\n\x07Request\x12(\n\x0bthreat_info\x18\x02 \x02(\x0b\x32\x13.Request.ThreatInfo\x1a\x61\n\nThreatInfo\x12\x37\n\x0ethreat_entries\x18\x03 \x03(\x0b\x32\x1f.Request.ThreatInfo.ThreadEntry\x1a\x1a\n\x0bThreadEntry\x12\x0b\n\x03url\x18\x02 \x02(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'threat_matches_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=25
  _globals['_REQUEST']._serialized_end=175
  _globals['_REQUEST_THREATINFO']._serialized_start=78
  _globals['_REQUEST_THREATINFO']._serialized_end=175
  _globals['_REQUEST_THREATINFO_THREADENTRY']._serialized_start=149
  _globals['_REQUEST_THREATINFO_THREADENTRY']._serialized_end=175
# @@protoc_insertion_point(module_scope)
